# Used for %time% placeholder.
# Formats/examples: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
time-format: 'dd/MM/yyyy'

# TabList. Header & footer.
# Use %ping%, %player-name%, %display-name%, %ip%, %time%, %server%, %server-online%, %ram-used%,
# %ram-max%, %ram-free%, %player-language% placeholder.
tablist:
  # Enable tablist header & footer?
  enable: true
  # Disabled servers, where you can not see the tab.
  disabled-servers:
  - someserver
  - servername
  # Blacklisted players, where the player not see the tab.
  blacklisted-players: []
  # How often to refresh the tablist (in milliseconds).
  refresh-interval: 50
  header:
    - '&2Tab&6List'
    - '&7<93>&3 Welcome&e &l%player-name%&7! <91>'
    - '&7<9>&6 Players:&e %server-online%&8/&e%max-players%&7 <10>'
    - '&5&l&m================='
  footer:
    - '&5&l&m================='
    - '&7Website:&2 example.com'
  # Per player tablist.
  per-player:
    playername:
      header:
        - '&2Tab&6List'
        - '&7<93>&3 Welcome&e &l%player-name%&7! <91>'
        - ''
        - '&5&l&m================='
      footer:
        - '&5&l&m================='
    someone:
      header:
        - '&7<93>&3 Welcome&e &l%player-name%&7! <91>'
        - ''
        - '&5&l&m================='
      footer:
        - '&5&l&m================='
  # Per server tablist.
  per-server:
    pvp:
      header:
        - '&7<93>&3 Welcome&e &l%player-name%&7! <91>&6 to&4 M&ay&3 Kit&4PvP&9 S&6e&2r&8v&5e&1r&6!'
      footer:
        - '&aGo to the PvP server!'
    lobby:
      header:
        - '&7<93>&3 Welcome&e &l%player-name%&7! <91>&6 to&4 M&ay&9 S&6e&2r&8v&5e&1r&6!'
      footer:
        - '&7<28>&a Choose a minigame or server and start playing!&7 <28>'
      per-player:
        exampleplayer:
          header:
            - ''
          footer:
            - '&7Website&7: example.org'

# Plugin messages.
messages:
  reload-config: '&aThe plugin successfully reloaded!'
  no-permission: '&cYou don''t have permission for this!'
  plugin-disabled: '&cThe plugin successfully disabled!'
  toggle:
    enabled: '&aThe tab is successfully turned on!'
    disabled: '&cThe tab is successfully turned off!'
    no-player: '&cThere is no player available on the server.'
  chat-messages:
  - '&8&l-----------'
  - '§7/§atablist reload&7 (or rl)§e -§6 Reloads the plugin and config.'
  - '§7/§atablist disable§e -§6 Disable the plugin.'
  - '&8&l-----------'

# DO NOT CHANGE THIS!
config-version: 3
