#=========================================#
#                Settings                 #
#=========================================#
# Used for %time% placeholder.
# Formats/examples: https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html
time-format: 'dd/MM/yyyy'

# TabList. Header & footer with animation.
# Use %max-players%, %ping%, %player-name%, %display-name%, %ip%, %time%, %server%, %server-online%, 
# %ram-used%, %ram-max%, %ram-free%, %player-language% placeholder.
# Use %animated-text:name% variable. - name, what you specified in the animations.yml file.
tablist:
  # Enable tablist header & footer?
  enable: true
  # Disabled servers, where you can not see the tab.
  disabled-servers:
  - someserver
  - servername
  # Blacklisted players, where the player not see the tab.
  blacklisted-players: []
  # How often to refresh the tablist (in milliseconds).
  refresh-interval: 50
  header:
    - '%animated-text:TabList%'
    - ''
    - '  &7&l>> %animated-text:welcome%&3 &l%player-name%&7&l! &7&l<<'
    - '&7<9>&6 Players:&e %server-online%&8/&e%max-players%&7 <10>'
    - ''
    - '%animated-text:playeranim%'
  footer:
    - '%animated-text:playeranim%'
    - ''
    - '%animated-text:web%&2 example.com'
  # Per player tablist.
  per-player:
    playername:
      header:
        - '%animated-text:TabList%'
        - '%animated-text:welcome%&a %player-name%&6!'
        - ''
        - '%animated-text:playeranim%'
      footer:
        - '%animated-text:playeranim%'
    someone:
      header:
        - '%animated-text:welcome%&a %player-name%&6!'
        - ''
        - '%animated-text:playeranim%'
      footer:
        - '%animated-text:playeranim%'
  # Per server tablist.
  per-server:
    pvp:
      header:
        - '%animated-text:welcome%&6 to&4 M&ay&3 Kit&4PvP&9 S&6e&2r&8v&5e&1r&6!'
      footer:
        - '&aGo to the PvP server!'
    lobby:
      header:
        - '%animated-text:welcome%&6 to&4 M&ay&9 S&6e&2r&8v&5e&1r&6!'
      footer:
        - '&7<28>&a Choose a minigame or server and start playing!&7 <28>'
      per-player:
        exampleplayer:
          header:
            - ''
          footer:
            - '%animated-text:web%&7: example.org'

# Plugin messages.
messages:
  reload-config: '&aThe plugin successfully reloaded!'
  no-permission: '&cYou don''t have permission for this!'
  plugin-disabled: '&cThe plugin successfully disabled!'
  toggle:
    enabled: '&aThe tab is successfully turned on!'
    disabled: '&cThe tab is successfully turned off!'
    no-player: '&cThere is no player available on the server.'
  chat-messages:
  - '&8&l-----------'
  - '§7/§atablist reload&7 (or rl)§e -§6 Reloads the plugin and config.'
  - '§7/§atablist disable§e -§6 Disable the plugin.'
  - '&8&l-----------'

# DO NOT CHANGE THIS!
config-version: 3
