#=================================OOO====================================#
#                     TabList Configuration File                         #
#=================================OOO====================================#
# config.yml file. Plugin version: 1.3                                   #
# Author, created by: montlikadani                                       #
#=================================OOO====================================#
# [Default configurations]                                               #
# https://github.com/montlikadani/TabList/blob/master/config.yml         #
#                                                                        #
# [Placeholders]                                                         #
# https://www.spigotmc.org/wiki/placeholderapi-placeholders/             #
#                                                                        #
# [Other placeholders]                                                   #
# https://github.com/montlikadani/TabList/wiki/Placeholders              #
#                                                                        #
# [Tips]                                                                 #
# - Use color coding '&' character, on this page:                        #
# http://minecraft.gamepedia.com/Formatting_codes                        #
# - In case of an error, write here:                                     #
# https://github.com/montlikadani/TabList/issues                         #
# - Use symbols in messages, on this page:                               #
# https://github.com/montlikadani/TabList/wiki/Symbols                   #
#=================================OOO====================================#

# If these number mark (#) are in the way, you can safely remove it.

#=========================================#
#                Settings                 #
#=========================================#
# PlaceholderAPI use for the plugin.
# It is not worth disabling because the plugin will not be perfect.
placeholderapi: true

# In what world do you use the tab?
# If you do not want to disable any of the worlds, then write it as follows: disabled-worlds: []
disabled-worlds:
- lobby
- hub

# The nickname is the maximum usable characters (including color codes and %space% placeholder).
nick-length: 30

# Save nick names and original player name (who changed their nickname) and UUID?
log-nicknames: true

# Which nicknames can not be used?
# If all the words are used, set it as follows: blacklist-nicknames: []
# WARNING! Color codes are NOT considered.
blacklist-nicknames:
- help
- nickname

# Do you want to change your nickname on your tab [TAB]?
change-tablist-name: true

# Allow to change the user display name?
change-displayname: true

# When the player left the server, delete the nickname?
clear-player-nick-on-quit: false

# Enable the default color. (If the player has not written a color code, this color will be given by default.)
default-nick-color:
  enable: false
  default-color: '&a'

# Allow color or code to be used on chat or on a tab.
# That is color tab or chat.
enable-color-code:
  chat: true
  tablist: true

# Allow the tab to set the level of life (health)?
# WARNING! This only appears in the server after reconnecting.
health-tab:
  enable: false
  # Which worlds show your health tab?
  # If you do not want to disable any of the worlds, then write it as follows: disabled-worlds: []
  disabled-worlds:
  - world
  - world_the_end

# Update tablist. (In ticks!)
# 20 tick - 1 second.
update-ticks: 60

# Enable the tab? (Header, footer)
tab-enable: true

# Tablist. Header & footer.
# Use %prefix%, \n, %staff-online%, %ip-address%, %mc-version%, %motd%, %ping%, %servername%, %online+1%, %max-players%, %online-players% placeholders.
# Use placeholders: https://www.spigotmc.org/wiki/placeholderapi-placeholders/
# Use symbols: https://github.com/montlikadani/TabList/wiki/Symbols
tablist:
  header: '&7<31>&b&l TabList&a created by:&6 montlikadani&7 <31>\n&7<75> &cWelcome&5 %player_name%&c!&7 <74>\n&6Ping:&a %ping%&7ms\n&5&m======================'
  footer: '&5&m======================&7\n<13>&e&l Players: &6%online-players%&7/&6%max-players%\n&c All players:&a %online+1%&7 <13>\n<28>&9 Website:&7 &nexample.com&7 <28>'

#=========================================#
#             Plugin Settings             #
#=========================================#
# The TabList plugin is disabled (false) or enabled (true).
# As this function is set to false, the plugin will shut itself down and no commands (which the plugin will detect) will be detected.
# To reload, write to true and refresh the server /reload.
enabled: true

# bStats Metrics.
metrics: true

# Check for updates.
check-update: true

# Log in to the console with plugin messages.
logconsole: true

# Logging to file plugin messages.
log-to-file: true

# Plugin enable/disable messages in console.
# Use %prefix%, %newline% placeholder.
# >> NO supported the PlaceholderAPI! <<
plugin-enable-message: true
plugin-enable: '%prefix%&a The plugin successfully enabled&6 v1.3&a!'
plugin-disable-message: true
plugin-disable: '%prefix%&c The plugin successfully disabled!'

# The default is allowed to see the plugin information.
# Permission: tablist.plugininfo
default-can-see-plugin-information: false

# Command waiting period.
# If you set it to 0 you will not have to wait.
# Measured in seconds. 1 seconds - 20 ticks.
# (This feature is known that there is no excessive lagg.)
# Use %seconds% (This placeholder is valid only here), %newline%, %prefix% placeholder.
# >> NO supported the PlaceholderAPI! <<
command-wait-time: 3
command-wait: '%prefix%&c Please wait&7 %seconds%&c seconds to use again!'

# Unknown-command - If more than one word/letter you write to it.
# Example: /tl reload something...
# Use %newline%, %command%, %prefix% placeholder.
# %command% - When you type the command (example: /tablist), it writes the command to it.
# This feature is NOT enter into the unknown command Minecraft, it's just your own.
# >> NO supported the PlaceholderAPI! <<
unknown-command-enable: true
unknown-command: '%prefix%&c Unknown command.&7 Type "&f/%command% help&7" for help.'
