name: Build TabList

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        # JitPack does not supports 17+ versions of JDK and newest gradle yet
        java-version: 17
        distribution: 'temurin'

    - name: Build all
      run: ./gradlew clean build --parallel

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: tablist-dev
        path: |
          !${{ github.workspace }}/bukkit/build/libs/*dev-all*.jar
          ${{ github.workspace }}/bukkit/build/libs/*bukkit*.jar
          !${{ github.workspace }}/bukkit/build/libs/*dev-all*.jar
          ${{ github.workspace }}/bungee/build/libs/*bungee*.jar
          ${{ github.workspace }}/sponge7/build/libs/tablist-sponge7*.jar
          ${{ github.workspace }}/sponge8/build/libs/tablist-sponge8*.jar
