name: Java CI with Maven

on:
  push:
    branches:
    - master
    - Sponge-7
    - Sponge-8

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Bukkit with Maven
      run: mvn -B package --file ${{ github.workspace }}/bukkit/pom.xml
      if: github.ref == 'refs/heads/master'
    - name: Upload Bukkit Artifact
      uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master'
      with:
        name: tablist-dev
        path: ${{ github.workspace }}/bukkit/target/TabList*.jar
    - name: Build Sponge-7 with Maven
      run: mvn -B package --file ${{ github.workspace }}/Sponge/pom.xml
      if: github.ref == 'refs/heads/Sponge-7'
    - name: Upload Sponge-7 Artifact
      uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/Sponge-7'
      with:
        name: tablist-sponge-dev
        path: ${{ github.workspace }}/Sponge/target/tablist-sponge*.jar
    - name: Build Sponge with Maven
      run: mvn -B package --file ${{ github.workspace }}/Sponge/pom.xml
      if: github.ref == 'refs/heads/Sponge-8'
    - name: Upload Sponge-8 Artifact
      uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/Sponge-8'
      with:
        name: tablist-sponge-dev
        path: ${{ github.workspace }}/Sponge/target/tablist-sponge*.jar
