name: Build TabList

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: Ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16
    - name: Build Bukkit with Maven
      run: mvn -B package --file ${{ github.workspace }}/bukkit/pom.xml
      if: github.ref == 'refs/heads/master'
    - name: Upload Bukkit Artifact
      uses: actions/upload-artifact@v2
      if: github.ref == 'refs/heads/master'
      with:
        name: tablist-dev
        path: ${{ github.workspace }}/bukkit/target/TabList*.jar
