name: Delete old workflow runs

on:
  schedule:
    - cron: '0 0 * * 0'
    # Run weekly, at 00:00 at sunday, https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule

jobs:
  del_runs:
    runs-on: ubuntu-latest
    if: github.event.schedule == '0 0 * * 0'
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 5
          keep_minimum_runs: 3